### ISSUE TITLE
Improve log, response & validation message

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/dhwani#4]

**Comment by mcastre** [comment]
could you provide more information on what kind of functionality you are looking for?

**Comment by sagar-jadhav** [comment]
- Use of [log](https://www.npmjs.com/package/log) NPM Module in all `*.js` files
- Improve existing logs. Add detailed logs with different log levels
- Add verbose response message on successful execution of different commands 
- Add verbose error/validation message on command execution with incomplete parameters

**Comment by mcastre** [comment]
Sweet. Ill do my best!

**Comment by sagar-jadhav** [comment]
@mcastre Thank you for contribution 👍 

I like the success & error message you have added.

Let me know if you are interested in collaborating with me on this project.
